/**
 * This file is automatically generated by scripts/fetch-posts.mjs
 * Do not edit manually.
 */
export const HEX_REDIRECTS: Record<string, string> = {
  "FFA500": "/color-orange-meaning/",
  "FFFF00": "/color-yellow-meaning/",
  "0000FF": "/color-blue-meaning/",
  "008000": "/color-green-meaning/",
  "FF0000": "/color-red-meaning/"
};
